# Top 14 selected features for CNN processing
# Generated by feature_selection_analysis.py

SELECTED_FEATURES = [
    'Length_of_Stay',
    'Appendix_Diameter',
    'CRP',
    'Peritonitis',
    'WBC_Count',
    'Alvarado_Score',
    'Neutrophil_Percentage',
    'Paedriatic_Appendicitis_Score',
    'Diagnosis_Presumptive',
    'Appendix_Wall_Layers',
    'Neutrophilia',
    'Body_Temperature',
    'Perforation',
    'Ileus',
]
